### ISSUE TITLE
A set of beautiful components!

### ISSUE THREAD

**Issue by edwinyzh** [HemulGM/Components#1]
I also viewed some of your other projects which seem to use this set of controls, the UI are all well-designed, clean and nice-looking, well done!

Just one question - what your version of Delphi, I'll see if I can make it compile-able with my XE4 :)

**Comment by edwinyzh** [comment]
Hello, it doesn't compiler under lower versions of Delphi (at least XE4).
When I find some time I'd like to fix that...

**Comment by HemulGM** [comment]
Thx) 
I work in the environment of RAD Studio 10.1 Berlin. At lower version did not check. I highly recommend that you upgrade too. We will definitely make a pull if changes are required in XE4.

**Comment by edwinyzh** [comment]
Thanks for the reply. I'll make a pull request when I have one.
