### ISSUE TITLE
File PngComponentsD not found

### ISSUE THREAD

**Issue by jkour** [HemulGM/Components#2]
I tried to install the package but the above file is not found. Where do I get it from?

Also, are these FMX components?

Thanks

**Comment by jkour** [comment]
Hi again,
I found the PNGComponents but now the sample does not run. There is an AV in Form8 with some property that is not serialised correctly. I am on 10.4. Which version are you using?

**Comment by HemulGM** [comment]
I use 10.3.3 CE.
Example may be out of date.
PNGComponents can be installed from GetIt. Or try delete letter "D" from PngComponentsD.
FMX is not supported for visual components and most likely will not.

**Comment by HemulGM** [comment]
GitHub did not notify me of new issues, sorry

**Comment by jkour** [comment]
No worries.
Thanks for the tip
